"""Bounded cold-ESP launch candidate; no molecular-model acceptance.

The read-only core and wrapper have separate implementation reviews. Actual
execution still requires a terminal, checked parent and a complete bound ESP
request. The generic child lifecycle is imported byte-for-byte from the already
reviewed local supervisor. Existing jobs are never reused.
"""
from __future__ import annotations

import argparse
import fcntl
import hashlib
import json
import os
from pathlib import Path
import shutil
import time
import types

CACHE = Path('/Users/ashujo/.cache/dynamol-research/6oim-resp-recovery-v1')
QM_PREFIX = Path('/Users/ashujo/.cache/dynamol-runtimes/qm-parallel-local-v1')
PLAN = CACHE/'prepared/plan-v3-resp-admitted.json'
PLAN_SHA = '8753021db5fe96d71fffcb29e7198b4ecf7b8668343389c9f110b81d76e43a20'
CORE = CACHE/'prepared/cold-evidence-core-v3/recovery_cold_evidence_core.py'
CORE_SHA = 'e160aee512211df052261b1ef11b4277e81fd192cf71369dbd5c5f466674e187'
LAUNCH_ADMITTED = True
MATERIALIZER_SHA = '698c6d6727e365860e3d00debbf060c216425e31f6f7e1a6ac7d55eb0237fab2'
SUPERVISOR = Path('/Users/ashujo/.cache/dynamol-research/6oim-local-recovery-v2-memory2000/local_qm_supervisor.py')
SUPERVISOR_SHA = 'e3f1ac0b86d2d9d13e2796ac564439eea76a93a39e554033f93b5a36cb1eec18'
WORKER = CACHE/'prepared/sources/qm_worker.py'
WORKER_SHA = 'ddb67a1f8e9be6ed05c3c95e9864e20b79f0233604e27926e30e5ffc09295bc1'
RUNTIME_SHA = '91a060defde8a3506861dffbb5277a4672bbfd041208c2cbbfeedb66dfe0c1b9'
INVENTORY = QM_PREFIX/'local-recovery-evidence/runtime-files.json'
INVENTORY_SHA = '683b958788605f35ce2fc9a5b7ac94edb03f5316bd0b166cfcb415ffaea1f416'
LIMITS = dict(native_memory_mb=2000, threads=2, max_process_rss_bytes=8_000_000_000,
              max_group_rss_bytes=8_000_000_000, native_wall_seconds=14400,
              outer_wall_seconds=14520, entry_disk_bytes=35*1024**3,
              running_disk_bytes=8*1024**3)
MATERIALIZED_FILES = {'result.json', 'exact-esp-input.json', 'parent-binding.json',
                      'geometry.json', 'downstream-contract.json'}
NATIVE_FILES = {'input.json', 'resolved-input.json', 'native.log', 'runtime-manifest.json',
                'progress.json', 'resolved-method.json', 'arrays.npz', 'scf.chk', 'result.json'}


def require(value, message):
    if not value:
        raise ValueError(message)


def raw(path, expected=None):
    path = Path(path)
    require(path.is_file() and not path.is_symlink(), 'Missing or nonregular file: '+str(path))
    content = path.read_bytes()
    require(len(content) == path.stat().st_size, 'Incomplete file read')
    if expected is not None:
        require(hashlib.sha256(content).hexdigest() == expected, 'Pinned bytes changed: '+str(path))
    return content


def sha(path):
    return hashlib.sha256(raw(path)).hexdigest()


def load(path, expected=None):
    return json.loads(raw(path, expected))


def module(path, expected, name):
    content = raw(path, expected)
    result = types.ModuleType(name)
    result.__file__ = str(path)
    exec(compile(content, str(path), 'exec'), result.__dict__)
    return result


def write(path, value):
    temporary = path.with_suffix(path.suffix+'.tmp')
    with temporary.open('w') as handle:
        json.dump(value, handle, indent=2, allow_nan=False)
        handle.write('\n')
        handle.flush()
        os.fsync(handle.fileno())
    temporary.replace(path)


def inventory(folder, names):
    folder = Path(folder)
    require(folder.is_dir() and not folder.is_symlink() and
            {p.name for p in folder.iterdir()} == set(names), 'Artifact inventory mismatch')
    return {name: sha(folder/name) for name in sorted(names)}


def verify_runtime():
    data = load(INVENTORY, INVENTORY_SHA)
    require(data['runtime'] == str(QM_PREFIX), 'Wrong runtime prefix')
    expected = {entry['relative_path'] for kind in ('files', 'symlinks') for entry in data[kind]}
    observed = set()
    for root, directories, files in os.walk(QM_PREFIX, followlinks=False):
        if Path(root) == QM_PREFIX:
            require(not (QM_PREFIX/'local-recovery-evidence').is_symlink(), 'Evidence directory is a symlink')
            directories[:] = [name for name in directories if name != 'local-recovery-evidence']
        for name in directories[:]:
            path = Path(root)/name
            if path.is_symlink():
                observed.add(path.relative_to(QM_PREFIX).as_posix())
                directories.remove(name)
        for name in files:
            path = Path(root)/name
            relative = path.relative_to(QM_PREFIX).as_posix()
            # The qualified inventory excludes generated bytecode. Child -B
            # plus a fresh pycache_prefix prevents reading or creating it.
            if path.parent.name == '__pycache__' and path.suffix == '.pyc' and not path.is_symlink():
                continue
            observed.add(relative)
    require(observed == expected, 'Unexpected executable/runtime payload inventory')
    for entry in data['files']:
        path = Path(entry['path'])
        require(path == QM_PREFIX/entry['relative_path'] and path.resolve().is_relative_to(QM_PREFIX),
                'Runtime file escaped prefix')
        content = raw(path, entry['sha256'])
        require(len(content) == entry['bytes'], 'Runtime file size changed')
    for entry in data['symlinks']:
        path = Path(entry['path'])
        require(path == QM_PREFIX/entry['relative_path'] and path.is_symlink() and
                os.readlink(path) == entry['link_target'] and str(path.resolve()) == entry['resolved_path'],
                'Runtime interpreter/library link changed')
        raw(path.resolve(), entry['resolved_sha256'])
    raw(QM_PREFIX/'dynamol-qm-runtime.json', RUNTIME_SHA)


def verify_native(folder, exit_code, input_sha256):
    """Execution integrity only; the independent reader owns ESP science checks."""
    require(type(exit_code) is int and exit_code == 0, 'Native child failed')
    hashes = inventory(folder, NATIVE_FILES)
    result = load(folder/'result.json')
    require(type(result.get('schema_version')) is int and result['schema_version'] == 1 and
            result.get('accepted') is True and result.get('status') == 'completed' and
            result.get('scf', {}).get('converged') is True, 'Native result is not numerically complete')
    require(result.get('input_sha256') == input_sha256 == hashes['input.json'] and
            result.get('worker_sha256') == WORKER_SHA, 'Native input/worker binding mismatch')
    for name, key in [('arrays.npz', 'arrays_sha256'), ('resolved-method.json', 'resolved_method_file_sha256'),
                      ('scf.chk', 'checkpoint_sha256')]:
        require(hashes[name] == result.get(key), 'Native output binding mismatch: '+name)
    require(hashes['runtime-manifest.json'] == RUNTIME_SHA and
            result.get('runtime_manifest', {}).get('sha256') == RUNTIME_SHA, 'Native runtime changed')
    require(load(folder/'progress.json') == {'phase': 'completed', 'status': 'completed', 'accepted': True},
            'Native progress is not terminal')
    return hashes


def failure_details(state, error, supervisor):
    """Preserve an observed bound crossing and uncertainty about child cleanup."""
    details = dict(error_type=type(error).__name__, error=str(error))
    if isinstance(error, MemoryError):
        try:
            sample = json.loads(str(error).split(': ', 1)[1])
            for key in ('maximum_process_rss_bytes', 'process_group_rss_bytes'):
                require(type(sample[key]) is int and sample[key] >= 0, 'Invalid crossing sample')
            details['error_observed_resource_sample'] = sample
            details['peak_sampled_process_rss_bytes'] = max(state['peak_sampled_process_rss_bytes'], sample['maximum_process_rss_bytes'])
            details['peak_sampled_group_rss_bytes'] = max(state['peak_sampled_group_rss_bytes'], sample['process_group_rss_bytes'])
        except (ValueError, KeyError, IndexError, TypeError):
            pass  # The complete original exception is always retained above.
    pid = state.get('child_pid')
    if pid is None:
        details.update(child_pid=None, cleanup_state=state.get('cleanup_state', 'no_child_launched'))
    else:
        try:
            alive = supervisor._group_is_alive(pid)
            details.update(child_pid=pid if alive else None,
                           cleanup_state='live_group_requires_attention' if alive else 'verified_no_live_group')
        except Exception as check_error:
            details.update(child_pid=pid, cleanup_state='unknown_requires_attention', cleanup_check_error=str(check_error))
    return details


def run(materialized, output):
    output = Path(output).resolve()
    require(output.is_relative_to(CACHE) and not output.exists(), 'Use a new directory in local recovery storage')
    output.mkdir(parents=True, exist_ok=False)
    state = dict(schema_version=1, status='preflight', child_pid=None, controller_pid=os.getpid(),
                 started_unix=time.time(), physical_acceptance=False, simulation_ready=False,
                 core_sha256=CORE_SHA, materializer_sha256=MATERIALIZER_SHA,
                 controller_sha256=sha(__file__), worker_sha256=WORKER_SHA,
                 runtime_manifest_sha256=RUNTIME_SHA, runtime_inventory_sha256=INVENTORY_SHA,
                 limits=LIMITS, peak_sampled_process_rss_bytes=0, peak_sampled_group_rss_bytes=0)

    def update(**values):
        state.update(values)
        state['updated_unix'] = time.time()
        write(output/'controller-progress.json', state)

    supervisor = None
    try:
        update()
        require(LAUNCH_ADMITTED and CORE is not None and CORE_SHA is not None,
                'Cold ESP launcher/core independent admission is pending; no child launched')
        core = module(CORE, CORE_SHA, 'reviewed_cold_evidence_core')
        context = core.revalidate_actual_parent(PLAN)
        raw(PLAN, PLAN_SHA)
        core.verify_materialized_request(materialized, context)
        hashes = inventory(materialized, MATERIALIZED_FILES)
        captured = output/'materialized'
        captured.mkdir()
        for name, expected in hashes.items():
            (captured/name).write_bytes(raw(Path(materialized)/name, expected))
        core.verify_materialized_request(captured, context)
        require(inventory(captured, MATERIALIZED_FILES) == hashes, 'Materialized capture changed')
        request = load(captured/'exact-esp-input.json')
        require('initial_checkpoint' not in request, 'Cold ESP cannot use a checkpoint')
        (output/'input.json').write_bytes(raw(captured/'exact-esp-input.json'))
        (output/'qm_worker.py').write_bytes(raw(WORKER, WORKER_SHA))
        (output/'controller-source.py').write_bytes(raw(__file__, state['controller_sha256']))
        spec = dict(schema_version=1, parent=str(core.materializer_module().PARENT),
                    plan_sha256=PLAN_SHA, core_sha256=CORE_SHA, materializer_sha256=MATERIALIZER_SHA,
                    materialized_hashes=hashes, input_sha256=sha(output/'input.json'),
                    worker_sha256=WORKER_SHA, controller_sha256=state['controller_sha256'],
                    runtime_manifest_sha256=RUNTIME_SHA, runtime_inventory_sha256=INVENTORY_SHA,
                    supervisor_sha256=SUPERVISOR_SHA, limits=LIMITS)
        write(output/'launch-spec.json', spec)
        update(spec_sha256=sha(output/'launch-spec.json'), input_sha256=spec['input_sha256'],
               materialized_hashes=hashes)
        supervisor = module(SUPERVISOR, SUPERVISOR_SHA, 'reviewed_generic_supervisor')
        verify_runtime()
        scratch = output/'scratch'
        scratch.mkdir()
        bytecode = scratch/'unused-bytecode'
        bytecode.mkdir()
        env = dict(os.environ)
        for key in ('PYTHONPATH', 'PYTHONHOME', 'DYLD_LIBRARY_PATH', 'DYLD_FALLBACK_LIBRARY_PATH'):
            env.pop(key, None)
        env.update(TMPDIR=str(scratch), PYSCF_TMPDIR=str(scratch), PYTHONDONTWRITEBYTECODE='1')
        for key in ('OMP_NUM_THREADS', 'OPENBLAS_NUM_THREADS', 'MKL_NUM_THREADS',
                    'VECLIB_MAXIMUM_THREADS', 'NUMEXPR_NUM_THREADS'):
            env[key] = '2'
        lock_path = Path('/Users/ashujo/Documents/Science/DynaMol/build/advanced-chemistry/QM-LAUNCH.lock')
        with lock_path.open('a') as lock:
            fcntl.flock(lock, fcntl.LOCK_EX | fcntl.LOCK_NB)
            require(not any(supervisor.is_qm_worker(row) for row in supervisor.process_rows()),
                    'Cold ESP is serial; another QM worker is active')
            require(shutil.disk_usage(output).free >= LIMITS['entry_disk_bytes'], 'Insufficient entry disk reserve')
            core.verify_materialized_request(captured, core.revalidate_actual_parent(PLAN))
            raw(output/'input.json', state['input_sha256'])
            raw(output/'qm_worker.py', WORKER_SHA)

            def started(pid):
                update(status='running', child_pid=pid, qm_started_unix=time.time())
                fcntl.flock(lock, fcntl.LOCK_UN)

            def sampled(sample):
                state['peak_sampled_process_rss_bytes'] = max(state['peak_sampled_process_rss_bytes'], sample['maximum_process_rss_bytes'])
                state['peak_sampled_group_rss_bytes'] = max(state['peak_sampled_group_rss_bytes'], sample['process_group_rss_bytes'])
                update(resource_sample=sample)
                require(sample['process_group_rss_bytes'] <= LIMITS['max_group_rss_bytes'], 'Owned process group exceeded sampled RSS bound')

            code = supervisor.supervise([str(QM_PREFIX/'bin/python'), '-I', '-B',
                                         '-X', 'pycache_prefix='+str(bytecode), str(output/'qm_worker.py'),
                                         str(output/'input.json'), str(output/'native')], output,
                                        LIMITS['outer_wall_seconds'], env, started, sampled,
                                        LIMITS['max_process_rss_bytes'], LIMITS['running_disk_bytes'])
        update(child_pid=None, exit_code=code, cleanup_state='verified_no_live_group')
        verify_runtime()
        raw(SUPERVISOR, SUPERVISOR_SHA)
        raw(CORE, CORE_SHA)
        raw(__file__, state['controller_sha256'])
        raw(output/'controller-source.py', state['controller_sha256'])
        raw(output/'launch-spec.json', state['spec_sha256'])
        raw(output/'qm_worker.py', WORKER_SHA)
        raw(output/'input.json', state['input_sha256'])
        core.verify_materialized_request(captured, core.revalidate_actual_parent(PLAN))
        require(inventory(captured, MATERIALIZED_FILES) == hashes, 'Captured request changed during execution')
        native_hashes = verify_native(output/'native', code, state['input_sha256'])
        update(status='numerically_complete_pending_esp_review', native_hashes=native_hashes,
               result_sha256=native_hashes['result.json'], completed_unix=time.time())
    except Exception as error:
        update(status='failed', **failure_details(state, error, supervisor))
    write(output/'controller-result.json', state)
    return state


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--materialized', required=True, type=Path)
    parser.add_argument('--output', required=True, type=Path)
    args = parser.parse_args()
    outcome = run(args.materialized, args.output)
    print(json.dumps(outcome, indent=2))
    raise SystemExit(0 if outcome['status'] == 'numerically_complete_pending_esp_review' else 1)
